# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # server
    - name: Setup Node.js for server
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: npm ci
      run: |
        cd server
        npm ci
        npm run build --if-present
        npm test

      # client
    - name: Setup Node.js for client
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies for client
      run: |
        cd client
        npm ci
        npm run build

      # heroku
      # from https://github.com/marketplace/actions/deploy-to-heroku
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh 
        echo "heroku-cli installed"
        
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/brimocars-bean-game.git
        git push heroku main  # This triggers a deploy on Heroku from GitHub